### ISSUE TITLE
Address upgrading between owncloud releases

### ISSUE THREAD

**Issue by l3iggs** [l3iggs/docker-owncloud#21] opened 2015-05-06 12:51 UTC
Some sort of migration/upgrade needs to be done to bring things like the database up to speed when switching from one ownCloud release to the next.

**Comment by l3iggs** [comment] 2015-10-31 16:36
Probably the instructions here should be adapted/added to for this image: https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html?highlight=upgrade

**Comment by kostko** [comment] 2015-11-13 17:00
The problem is also that ownCloud's migration system does not support upgrading between major versions. So if you skip a version (which can easily happen), you cannot upgrade from 8.0 to 8.2 later. And if you use the Docker image, there are also no historical tags so that you could easily first upgrade to 8.1 and then to 8.2.

So I think that you should consider adding per-version tags to your Docker image.

To work around this issue, I used a specific Arch package snapshot from 2015-10-20 to upgrade to 8.1 and then the latest snapshot to upgrade to 8.2. Perhaps you could use specific snapshots in your releases to prevent unintended upgrades.

**Comment by l3iggs** [comment] 2015-11-14 09:38
Very good points. https://github.com/l3iggs/docker-owncloud/issues/48

**Comment by mitar** [comment] 2015-11-25 09:19
+1

**Comment by l3iggs** [comment] 2015-11-27 16:40
@kostko, @mitar I've now added tags to the docker image. That should hopefully alleviate some of the pain here.

**Comment by greyltc** [comment] 2016-03-14 11:08
The ownCloud folks seem to have addressed this with their new updater app in the version 9.0 that was just released: https://doc.owncloud.org/server/9.0/admin_manual/maintenance/update.html

I haven't honestly tried it, but it appears to solve this issue so I'll close it.

**Closed as completed by greyltc** 2016-03-14 11:08 UTC
Labels: enhancement

**Comment by mitar** [comment] 2016-03-14 15:44
@greyltc: But does ownCloud now support upgrading by skipping versions? Previously, one had to upgrade manually version by version. But what if I am for example running Docker image for ownCloud 7, and upgrade code to Docker image for ownCloud 9. Will ownCloud upgrade correctly?

**Comment by greyltc** [comment] 2016-03-14 16:14
I'm very doubtful that going right from 7->9 would be a smooth transition for you.
It looks like the OC documentation [here](https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html) has some words on that.

**Comment by mitar** [comment] 2016-03-14 16:31
OK, then let's open a ticket about this. Because it is really hard to assure that upgrading is doing a step-wise way when one uses Docker images. You do `docker pull` and you get some version you do not know it will break your upgrade process because it skipped one in between.

Other software simply applies all missed migrations in order. It does not require that you manually go one by one version.

Should we open another ticket or just reopen this one?

**Comment by greyltc** [comment] 2016-03-14 17:37
My solution to unexpected upgrades via the "who knows what you get when you do a `docker pull l3iggs/owncloud`" problem is to start tagging the release containers. That way you can specify what owncloud image version to stay on by specifying a tag like so:
`docker pull l3iggs/owncloud:9.0.0-1`
and get no unexpected upgrades. Then you can also move between versions only when you're ready.

Using `docker pull l3iggs/owncloud` is equivalent to `docker pull l3iggs/owncloud:latest`

You can see the tags I've made here: https://hub.docker.com/r/l3iggs/owncloud/tags/

I only started doing this at `8.2.2-1` so it doesn't really help if you're coming from version 7.

Do you think that addresses the issue?
